import "./globals.css";
import Footer from "./ui/footer/Footer";
import Header from "./ui/header/Header";
import { MainNav } from "./ui/mainNav/MainNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {/* <Header></Header> */}
        {children}
        <Footer/>
        </body>
    </html>
  );
}
